#pragma once

enum class GameState { MENU, PLAYING, PAUSED, GAME_OVER, SCORE_SELECTION, TIME_SELECTION, OPPONENT_SELECTION, DIFFICULTY_SELECTION };
enum class GameMode { CLASSIC, TIMED, SCORING, RANDOM_EVENTS };
enum class OpponentType { PLAYER_VS_PLAYER, PLAYER_VS_BOT };
enum class RandomEvent { NOTHING, SCORE_PLUS_10, SCORE_MINUS_10, SCORE_PLUS_25, SCORE_MINUS_25, BONUS_MOVE, SWAP_PLAYERS, CLEAR_AREA };
enum class BotDifficulty { EASY, MEDIUM, HARD };
